### ISSUE TITLE
Support transforming old octal literals for strict mode

### ISSUE THREAD

**Issue by guybedford** [jspm/babel-plugin-transform-cjs-dew#12]
Literals like `"\033[90m"` and `01` are banned in strict mode, so should be supported as part of the conversion process into strict.

**Comment by rhalff** [comment]
For reference, here is an example of a module containing such unimportable code: https://dev.jspm.io/npm:github@0.2.4/util.dew.js

**Comment by guybedford** [comment]
To explain the fix, the plugin here would need to replace `"\033[90m"` with the strict-mode-compatible escape sequence `"\u001b[90m"`. That is, detecting octal sequences like `\033` in strings and replacing it with the correct escape sequence `\u001b`.

**Comment by guybedford** [comment]
This has been fixed.
